FROM python:3.7.2-alpine3.9

ENV FLASK_APP=informatics_front.wsgi.py:application

RUN apk update
RUN apk add gcc libressl-dev musl-dev libffi-dev

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt
CMD sleep 30 && flask test