"""empty message

Revision ID: 16a803b04a4f
Revises: 54aadcd20b58
Create Date: 2019-06-11 19:00:25.623914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a803b04a4f'
down_revision = '54aadcd20b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('protocol_visibility', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'protocol_visibility')
    # ### end Alembic commands ###
