"""empty message

Revision ID: 4a1111762ca4
Revises: 54aadcd20b58
Create Date: 2019-07-02 19:05:58.840733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1111762ca4'
down_revision = '54aadcd20b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('owner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.create_unique_constraint('_user_refresh_token_uc', 'refresh_token',
                                ['user_id', 'token'],
                                schema='pynformatics')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'owner_id')
    # ### end Alembic commands ###
    op.drop_constraint('_user_refresh_token_uc', 'refresh_token', schema='pynformatics')
