"""empty message

Revision ID: 54aadcd20b58
Revises: c1ba34f5e083
Create Date: 2019-05-23 13:04:50.273135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aadcd20b58'
down_revision = 'c1ba34f5e083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('access_token', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'access_token')
    # ### end Alembic commands ###
