"""empty message

Revision ID: 9b49c7310323
Revises: c1ba34f5e083
Create Date: 2019-06-07 17:53:10.164425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b49c7310323'
down_revision = 'c1ba34f5e083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('protocol_visibility', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'protocol_visibility')
    # ### end Alembic commands ###
