"""empty message

Revision ID: a6a54a1a8e5b
Revises: 
Create Date: 2019-04-19 12:57:26.784422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a54a1a8e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_stop', sa.DateTime(), nullable=True),
    sa.Column('virtual_duration', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['pynformatics.workshop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('workshop_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['pynformatics.workshop.id'], name='fk_course_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workshop_id', name='_workshop_user_uc'),
    schema='pynformatics'
    )
    op.create_table('contest_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['pynformatics.contest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contest_id', name='_contest_user_uc'),
    schema='pynformatics'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_connection', schema='pynformatics')
    op.drop_table('workshop_connection', schema='pynformatics')
    op.drop_table('contest', schema='pynformatics')
    op.drop_table('workshop', schema='pynformatics')
    op.drop_table('refresh_token', schema='pynformatics')
    # ### end Alembic commands ###

