"""empty message

Revision ID: ed0a5543cfb6
Revises: 
Create Date: 2019-04-18 17:24:56.901022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import BIGINT

# revision identifiers, used by Alembic.
revision = 'ed0a5543cfb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('contest_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', BIGINT(display_width=10, unsigned=True), nullable=True), # <-> for
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_stop', sa.DateTime(), nullable=True),
    sa.Column('virtual_duration', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['moodle.mdl_statements.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['pynformatics.workshop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('user_id', BIGINT(unsigned=True), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['moodle.mdl_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('workshop_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['pynformatics.workshop.id'], name='fk_course_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workshop_id', name='_workshop_user_uc'),
    schema='pynformatics'
    )
    op.create_table('contest_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contest_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_instance_id'], ['pynformatics.contest_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contest_instance_id', name='_contest_user_uc'),
    schema='pynformatics'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_connection', schema='pynformatics')
    op.drop_table('workshop_connection', schema='pynformatics')
    op.drop_table('refresh_token', schema='pynformatics')
    op.drop_table('contest_instance', schema='pynformatics')
    op.drop_table('workshop', schema='pynformatics')
    # ### end Alembic commands ###
