"""empty message

Revision ID: f0c231b35250
Revises: 4a1111762ca4
Create Date: 2019-08-08 16:40:26.083716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c231b35250'
down_revision = '4a1111762ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pynformatics'
    )
    op.create_table('language_contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['pynformatics.contest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['pynformatics.languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'contest_id', name='_language_contest_uc'),
    schema='pynformatics'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_contest', schema='pynformatics')
    op.drop_table('languages', schema='pynformatics')
    # ### end Alembic commands ###
