# Generated by Django 2.2.1 on 2019-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'IOI'), (2, 'ACM'), (3, 'LightACM')], default=2)),
                ('user_visibility', models.IntegerField(choices=[(1, 'Ученик видит свои результаты'), (2, 'Ученик видит все результаты'), (3, 'Ученик не видит результаты')])),
                ('freeze_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contest_monitor',
                'managed': False,
            },
        ),
    ]
