# Generated by Django 2.2.1 on 2019-08-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workshopmonitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'managed': False, 'verbose_name': 'Контест', 'verbose_name_plural': 'Контесты'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'managed': False, 'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='workshopconnection',
            options={'managed': False, 'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterModelOptions(
            name='workshopmonitor',
            options={'managed': False, 'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
    ]
