# Generated by Django 2.2.1 on 2019-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190813_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=32)),
                ('mode', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'language_contest',
                'managed': False,
            },
        ),
    ]
